spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server.default.svc.cluster.local:8761/eureka

ribbon:
  eureka:
    enabled: false
  ReadTimeout: 60000
  ConnectTimeout: 20000



zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
    connection-request-timeout-millis: 30000
  routes:
    auth:
      path: /auth-service/**
      serviceId: auth-service
      sensitive-headers: Cookie,Set-Cookie
    catalog:
      path: /catalog-service/**
      serviceId: catalog-service
      sensitive-headers: Cookie,Set-Cookie
    user:
      path: /user-service/**
      serviceId: user-service
      sensitive-headers: Cookie,Set-Cookie
    cart:
      path: /cart-service/**
      serviceId: cart-service
      sensitive-headers: Cookie,Set-Cookie
    order:
      path: /order-service/**
      serviceId: order-service
      sensitive-headers: Cookie,Set-Cookie
    payment:
      path: /payment-service/**
      serviceId: payment-service
      sensitive-headers: Cookie,Set-Cookie

auth-service:
  ribbon:
    listOfServers: auth-service.default.svc.cluster.local:9100

catalog-service:
  ribbon:
    listOfServers: catalog-service.default.svc.cluster.local:9200

user-service:
  ribbon:
    listOfServers: user-service.default.svc.cluster.local:9300

cart-service:
  ribbon:
    listOfServers: cart-service.default.svc.cluster.local:9400

order-service:
  ribbon:
    listOfServers: order-service.default.svc.cluster.local:9500

payment-service:
  ribbon:
    listOfServers: payment-service.default.svc.cluster.local:9600
