{{- range $service, $val := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $service }}
{{- end }}